#!/usr/bin/env node
/**
 * build-ts.mjs — emit dist/tokens/tokens.ts: a typed, resolved snapshot of the
 * canonical token layer for TS consumers (Storybook docs, product tooling).
 * Not part of the npm package until the consumer-swap phase.
 *
 * Run: npm run tokens:build
 */
import { writeFileSync, mkdirSync } from "node:fs"
import { join } from "node:path"
import { loadTokens, resolveValue, repoRoot } from "./lib-tokens.mjs"

const { registry } = loadTokens()
mkdirSync(join(repoRoot, "dist", "tokens"), { recursive: true })

const entries = [...registry.values()]
  .sort((a, b) => a.path.localeCompare(b.path))
  .map((e) => {
    const value = resolveValue(registry, e.token.$value)
    return `  ${JSON.stringify(e.path)}: { value: ${JSON.stringify(value)}, cssVar: ${JSON.stringify(e.cssVar)}, type: ${JSON.stringify(e.token.$type ?? "unknown")}, layer: ${JSON.stringify(e.layer)} },`
  })

writeFileSync(
  join(repoRoot, "dist", "tokens", "tokens.ts"),
  `// AUTO-GENERATED by scripts/tokens/build-ts.mjs from tokens/**. Do NOT edit.
// Regenerate: npm run tokens:build

export const tokens = {
${entries.join("\n")}
} as const

export type TokenPath = keyof typeof tokens
export type TokenLayer = (typeof tokens)[TokenPath]["layer"]

/** \`var(--…)\` reference for a canonical token path. */
export const tokenVar = (path: TokenPath): string => \`var(\${tokens[path].cssVar})\`
`
)
console.log(`dist/tokens/tokens.ts — ${entries.length} tokens`)
