#!/usr/bin/env node
/**
 * lib-tokens.mjs — shared loader/registry/resolver for the canonical token
 * layer. Used by build-css / build-ts / build-contract / diff / audit-contrast.
 *
 * CSS variable naming (the deliberate deviation from the v2 spec's
 * `--color-background` style, documented in scripts/tokens/README.md):
 *
 *   primitive  --ll-<path>          --ll-color-slate-500, --ll-space-2-5
 *                                   (namespaced: Tailwind v4's default @theme
 *                                   owns --color-*, --text-*, --font-weight-*)
 *   semantic   shadcn-compatible    color.<key>  → --<key>   (--background,
 *                                   --primary-foreground — the shipped API
 *                                   that app/globals.css @theme maps onto)
 *              other roles          --<path>     (--surface-card,
 *                                   --focus-ring-width, --status-success)
 *   component  --<path>             --button-height-md, --table-cell-padding
 *
 * All names kebab-case; camelCase segments split (paddingX → padding-x).
 */
import { readFileSync, readdirSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

export const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..")
const tokensRoot = join(repoRoot, "tokens")

export const kebab = (s) =>
  s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase()
const pathToKebab = (p) => p.split(".").map(kebab).join("-")

/** css var name for a canonical token path */
export function cssVarName(layer, path) {
  if (layer === "primitive") return `--ll-${pathToKebab(path)}`
  if (layer === "semantic" && path.startsWith("color."))
    return `--${pathToKebab(path.slice("color.".length))}`
  return `--${pathToKebab(path)}`
}

const isToken = (n) => n && typeof n === "object" && "$value" in n
export const aliasOf = (v) =>
  typeof v === "string" ? /^\{(.+)\}$/.exec(v)?.[1] : undefined

function walk(node, path, cb) {
  if (node == null || typeof node !== "object") return
  if (isToken(node)) cb(node, path)
  for (const [k, v] of Object.entries(node))
    if (!k.startsWith("$")) walk(v, path ? `${path}.${k}` : k, cb)
}

/**
 * Load the whole canonical layer.
 * Returns { registry: Map<path, entry>, overlays: { mode: {...}, theme: {...} } }
 * entry = { path, layer, file, cssVar, token }
 */
export function loadTokens() {
  const registry = new Map()
  for (const layer of ["primitive", "semantic", "component"]) {
    for (const f of readdirSync(join(tokensRoot, layer)).sort()) {
      if (!f.endsWith(".json")) continue
      const json = JSON.parse(readFileSync(join(tokensRoot, layer, f), "utf8"))
      walk(json, "", (token, path) => {
        registry.set(path, { path, layer, file: `${layer}/${f}`, cssVar: cssVarName(layer, path), token })
      })
    }
  }
  const overlays = { mode: {}, theme: {} }
  for (const kind of ["mode", "theme"]) {
    for (const f of readdirSync(join(tokensRoot, kind)).sort()) {
      if (!f.endsWith(".json")) continue
      const json = JSON.parse(readFileSync(join(tokensRoot, kind, f), "utf8"))
      for (const [name, body] of Object.entries(json[kind] ?? {})) {
        const entries = []
        walk(body, "", (token, path) => entries.push({ path, token }))
        overlays[kind][name] = {
          file: `${kind}/${f}`,
          body,
          entries,
          proposed: /PROPOSED/i.test(String(json.$description ?? "")),
        }
      }
    }
  }
  return { registry, overlays }
}

/** Resolve a token's $value to its final literal (follows alias chains). */
export function resolveValue(registry, value, seen = new Set()) {
  const target = aliasOf(value)
  if (!target) return value
  if (seen.has(target)) throw new Error(`circular alias via {${target}}`)
  seen.add(target)
  const entry = registry.get(target)
  if (!entry) throw new Error(`unresolved alias {${target}}`)
  return resolveValue(registry, entry.token.$value, seen)
}

/** Emit a token's $value as CSS: alias → var(--…), string with spaces → quoted. */
export function cssValue(registry, value) {
  const target = aliasOf(value)
  if (target) {
    const entry = registry.get(target)
    if (!entry) throw new Error(`unresolved alias {${target}}`)
    return `var(${entry.cssVar})`
  }
  if (typeof value === "number") return String(value)
  if (/\s/.test(value) && !/[(),]/.test(value)) return JSON.stringify(value)
  return value
}

export const GENERATED_HEADER = (script) =>
  `/* AUTO-GENERATED by scripts/tokens/${script} from tokens/**. Do NOT edit.\n * Regenerate: npm run tokens:build */\n`
