/**
 * icons/icon-registry.ts — THE single icon gate for this design system.
 *
 * - `iconRegistry` maps curated kebab-case names → lucide components. It is
 *   the `<Icon name=…>` lookup, the `IconName` type source, and what
 *   `.designops/icon-contract.json` is generated from
 *   (scripts/registry/build-icon-contract.mjs regex-parses the REGISTRY block
 *   below — keep its one-entry-per-line format).
 * - The named re-exports at the bottom are the ONLY sanctioned way for
 *   components/stories to import icon components directly (both lucide
 *   spellings in current use are kept so the migration was a pure
 *   import-path swap).
 *
 * Rules (.designops/forbidden-patterns.md, enforced by `npm run audit:icons`):
 * - Do not import from "lucide-react" anywhere else. Sole exception:
 *   components/docs/references/icon-library.tsx (docs gallery needs the full
 *   `icons` map).
 * - New icons: add the lucide import + a REGISTRY entry here first.
 * - Custom brand SVGs live in icons/custom/ and must be registered here too.
 */
import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  Archive,
  ArrowUpDown,
  BadgeCheck,
  Bell,
  Bold,
  BookOpen,
  Bot,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleCheck,
  Clock,
  Copy,
  FolderOpen,
  Frame,
  GalleryVerticalEnd,
  GripVertical,
  Home,
  Inbox,
  Info,
  Italic,
  Loader2,
  Mail,
  Map,
  Minus,
  MoreHorizontal,
  OctagonX,
  Palette,
  PanelLeft,
  PieChart,
  Search,
  Settings,
  Settings2,
  SquareTerminal,
  Star,
  Terminal,
  TriangleAlert,
  Underline,
  X,
} from "lucide-react"

// REGISTRY (parsed by build-icon-contract.mjs — one entry per line)
export const iconRegistry = {
  "align-center": AlignCenter,
  "align-left": AlignLeft,
  "align-right": AlignRight,
  archive: Archive,
  "arrow-up-down": ArrowUpDown,
  "badge-check": BadgeCheck,
  bell: Bell,
  bold: Bold,
  "book-open": BookOpen,
  bot: Bot,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-up-down": ChevronsUpDown,
  "circle-check": CircleCheck,
  clock: Clock,
  close: X,
  copy: Copy,
  "folder-open": FolderOpen,
  frame: Frame,
  "gallery-vertical-end": GalleryVerticalEnd,
  "grip-vertical": GripVertical,
  home: Home,
  inbox: Inbox,
  info: Info,
  italic: Italic,
  loader: Loader2,
  mail: Mail,
  map: Map,
  minus: Minus,
  "more-horizontal": MoreHorizontal,
  "octagon-x": OctagonX,
  palette: Palette,
  "panel-left": PanelLeft,
  "pie-chart": PieChart,
  search: Search,
  settings: Settings,
  "settings-2": Settings2,
  "square-terminal": SquareTerminal,
  star: Star,
  terminal: Terminal,
  "triangle-alert": TriangleAlert,
  underline: Underline,
} as const

export type IconName = keyof typeof iconRegistry

/* Named re-exports — the sanctioned direct-import surface. */
export {
  AlignCenter,
  AlignLeft,
  AlignRight,
  Archive,
  ArrowUpDown,
  BadgeCheck,
  Bell,
  Bold,
  BookOpen,
  Bot,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleCheck,
  Clock,
  Copy,
  FolderOpen,
  Frame,
  GalleryVerticalEnd,
  GripVertical,
  Home,
  Inbox,
  Info,
  Italic,
  Loader2,
  Mail,
  Map,
  Minus,
  MoreHorizontal,
  OctagonX,
  Palette,
  PanelLeft,
  PieChart,
  Search,
  Settings,
  Settings2,
  SquareTerminal,
  Star,
  Terminal,
  TriangleAlert,
  Underline,
  X,
  // `*Icon` spellings used by components/ui (lucide ships both; keeping them
  // made the registry migration a pure import-path swap)
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  CircleCheck as CircleCheckIcon,
  GripVertical as GripVerticalIcon,
  Info as InfoIcon,
  Loader2 as Loader2Icon,
  Minus as MinusIcon,
  MoreHorizontal as MoreHorizontalIcon,
  OctagonX as OctagonXIcon,
  PanelLeft as PanelLeftIcon,
  Search as SearchIcon,
  TriangleAlert as TriangleAlertIcon,
  X as XIcon,
}
